# awsへアクセスする設定
name: aws config
description: aws access user and role config
inputs:
  AWS_ROLE_ARN:
    required: true
    description: aws role arn
  REGION:
    required: true
    description: resource region
outputs:
  ECR_REGISTRY:
    value: ${{ steps.login-ecr.outputs.registry }}
    description: ECR REGISTRY name
runs:
  using: composite
  steps:
    # aws のアカウント設定
    - name: Configure AWS credentials
      id: aws-config
      uses: aws-actions/aws-configure-credentials@v1
      with:
        aws-region: ${{ inputs.REGION }}
        role-to-assume: ${{ inputs.AWS_ROLE_ARN }}
        role-duration-seconds: 900
        role-skip-session-tagging: true
    # ECRへのログイン
    - name: Login ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1