version: '3'
services:
  backend:
    build:
      # contextでわざと最上階層まで戻しているのは、そのディレクトリ以下のファイルしかCOPYできないから
      context: ../
      dockerfile: docker/backend/Dockerfile
    container_name: 'webapp-sandbox-dev'
    image: webapp-sandbox-dev
    platform: linux/x86_64
    ports:
      - '8001:8080'
    volumes:
      - ../src/backend:/workdir
    tty: true

  mock-ui:
    container_name: 'swagger-ui'
    image: swaggerapi/swagger-ui
    ports:
      - '8002:8080'
    volumes:
      - ./backend/mock/swagger.yaml:/swagger.yaml
    environment:
      SWAGGER_JSON: /swagger.yaml

  mock:
    container_name: 'swagger-api'
    image: stoplight/prism:3
    ports:
      - '8003:4010'
    command: mock -h 0.0.0.0 /swagger.yaml
    volumes:
      - ./backend/mock/swagger.yaml:/swagger.yaml
