name: CD dev
# developにmergeされ、src/backend以下に変更があったときのみ更新
on:
  workflow_dispatch:
  push:
    branches:
      - "develop"
    paths:
      - "src/backend/**"

permissions:
  id-token: write
  contents: read

env:
  # ロールの作成方法：https://dev.classmethod.jp/articles/github-actions-oidc-configure-aws-credentials/
  AWS_ROLE_ARN: arn:aws:iam::749825783834:role/GithubWebappSandboxRole
  REGION: us-east-1

jobs:
  CD-dev:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup AWS credentials
        uses: ./.github/workflows/composite/aws-setup
        id: aws-setup
        with:
          AWS_ROLE_ARN: ${{ env.AWS_ROLE_ARN }}
          REGION: ${{ env.REGION }}

      - name: Setup docker
        uses: ./.github/workflows/composite/docker-setup
        id: docker-setup
        with:
          TARGET: backend

      - name: Update lambda
        uses: ./.github/workflows/composite/lambda-update
        id: lambda-update
        with:
          IMAGE_NAME: webapp-sandbox-dev
          LAMBDA_NAME: webapp-sandbox-dev
          ECR_REGISTRY: ${{ steps.aws-setup.outputs.ECR_REGISTRY }}
          REPOSITORY: webapp-sandbox-dev